//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace HL.Biblio.POCO
{
    public partial class Ejemplar {
        #region Primitive Properties

        public virtual int Id {
            get;
            set;
        }

        public virtual string Codigo {
            get;
            set;
        }

        public virtual string CodRFID {
            get;
            set;
        }

        public virtual string CodBarras {
            get;
            set;
        }

        public virtual int TipoPrestamo {
            get;
            set;
        }

        public virtual string Ubicacion {
            get;
            set;
        }

        public virtual int Estado {
            get;
            set;
        }

        #endregion
        #region Navigation Properties

        public virtual Libro Libro {
            get { return _libro; }
            set {
                if(!ReferenceEquals(_libro, value)) {
                    var previousValue = _libro;
                    _libro = value;
                    FixupLibro(previousValue);
                }
            }
        }
        private Libro _libro;

        #endregion
        #region Association Fixup

        private void FixupLibro(Libro previousValue) {
            if(previousValue != null && previousValue.Ejemplares.Contains(this)) {
                previousValue.Ejemplares.Remove(this);
            }

            if(Libro != null) {
                if(!Libro.Ejemplares.Contains(this)) {
                    Libro.Ejemplares.Add(this);
                }
            }
        }

        #endregion
    }
}
